11 upgrade to spring boot 30
dialob/dialob-parent pull request #124
Opened 2024-03-21 13:28 UTC by patope

2024-03-22 07:50 UTC, villuv requested changes

2024-03-22 07:50 UTC, villuv commented on docs/spring-boot-3.md
> +|| Old name         || New name              ||
Table formatting is broken

2024-03-22 07:51 UTC, villuv commented
dialob-boot and dialob-session-boot Dockerfiles need to switch to java 17 base image

2024-03-22 07:56 UTC, olev-mutso requested changes
Have you checked findbugs report?

2024-03-22 07:56 UTC, olev-mutso commented on dialob-build-parent/pom.xml
> +    <junit.jupiter.version>5.10.2	</junit.jupiter.version>
Remove spaces after version number.

2024-03-22 07:59 UTC, villuv requested changes
I built local docker images from this branch, replaced an existing local dev environment setup using v. 2.1 along with changing the redis parameter as instructed. Local configuration has ` DIALOB_SECURITY_ENABLED=false` configured.

I get 403 on OPTIONS http://localhost:8085/dialob/api/forms/xxx request

So either migration instructions are not complete or security disabled mode doesn't work.

2024-03-22 08:04 UTC, patope commented on dialob-components/dialob-questionnaire-service/src/main/java/io/dialob/questionnaire/service/DialobQuestionnaireServiceAutoConfiguration.java
> +  public EventPublisher questionnaireSessionEventPublisher(@Qualifier("applicationTaskExecutor") TaskExecutor taskExecutor, ApplicationEventPublisher applicationEventPublisher) {
Name is `applicationTaskExecutor` provided by Spring's `@EnableTaskExecutor`. `@EnableTaskScheduling` and `@EnableTaskExecutor` both define executors and trigger injection conflict.

2024-03-22 08:26 UTC, patope commented on dialob-components/dialob-integration-api/src/main/java/io/dialob/integration/api/event/FormTaggedEvent.java
It's not for `@Value.Immutable`. It's for semantic analyzers.

2024-03-22 10:29 UTC, patope commented
> **villuv ** requested changes

Auto configurations didnt work. Try again.

2024-03-22 10:30 UTC, patope commented on dialob-components/dialob-questionnaire-service/src/main/java/io/dialob/questionnaire/service/DialobQuestionnaireServiceAutoConfiguration.java
> +  public EventPublisher questionnaireSessionEventPublisher(@Qualifier("applicationTaskExecutor") TaskExecutor taskExecutor, ApplicationEventPublisher applicationEventPublisher) {
Replaced with constant `TaskExecutionAutoConfiguration.APPLICATION_TASK_EXECUTOR_BEAN_NAME`

2024-03-22 10:31 UTC, patope commented on dialob-components/dialob-cache/src/main/java/io/dialob/cache/DialobCacheAutoConfiguration.java
> +    public ScheduledSessionEvictionPolicy scheduledSessionEvictionPolicy(Optional<Clock> clock, Optional<QuestionnaireSessionSaveService> sessionService, Optional<CacheManager> cacheManager, DialobSe
Remove Clock bean

2024-03-25 14:05 UTC, patope commented on dialob-session-boot/src/main/resources/application.yml
>        webSocketEnabled: true
https://github.com/dialob/dialob-parent/blob/62a04f59b300570130fe640b4b3a58bcde79c133/docs/spring-boot-3.md

2024-03-25 14:07 UTC, patope commented on dialob-components/dialob-session-engine/src/main/java/io/dialob/session/engine/program/model/DisplayItem.java
> +import edu.umd.cs.findbugs.annotations.NonNull;
Uses only `edu.umd.cs.findbugs.annotations.NonNull` now

2024-06-07 16:00 UTC, merged